version: "2.1"
services:
  #
  # janus-gateway
  #
  janus-gateway:
    container_name: janus-gateway
    image: "canyan/janus-gateway:0.10.7"
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus", "-d", "7"]
    ports:
      - "8188:8188"
      - "8088:8088"
      # - "8089:8089"
      - "8889:8889"
      - "8000:8000"
      - "7088:7088"
      - "7089:7089"
    volumes:
      - "./etc/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./etc/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg"
      - "./etc/janus/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
      - "./etc/janus/janus.transport.websocket.jcfg:/usr/local/etc/janus/janus.transport.websocket.jcfg"
      - "./etc/janus/loggers:/usr/local/lib/janus/loggers"
      - "./cert:/janus/cert"

    restart: always

  web:
    container_name: web
    image: nginx:alpine
    restart: always
    volumes:
      - ./html:/var/www/html:z,ro
      - ./cert:/var/www/cert:z,ro
      - ./etc/janus.conf:/etc/nginx/conf.d/default.conf:z,ro
    ports:
      - 80:80
      - 443:443
      - "8089:8089"

  turn-server:
    build:
      context: ./turn-server
    container_name: turn-server
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    volumes:
      - ./turn-server/log:/var/log
      - ./turn-server/turndb:/var/lib/turn/turndb
      - ./turn-server/turnserver.conf:/etc/turnserver.conf
